phraseapp:
  access_token: "da610a054657f9aec5798ea6b25ed755d3aab0f767fb0f860a1d29dd0c22d238"
  project_id: "d5121075da19a296525da457398a569f"
  file_format: "csv"
  pull:
    targets:  
    - file: "./i18n/axi.json"
      params:
        file_format: "nested_json"
        locale_id: 626a0224e5e9620fbee69ceea2a1edae
    - file: "./i18n/en.json"
      params:
        file_format: "nested_json"
        locale_id: e5c60928f8f0fb2e34c75cb54b838220
    - file: "./i18n/sv.json"
      params:
        file_format: "nested_json"
        locale_id: 5b980190630bae4feefd272f24f5bbfb
    - file: "./i18n/da.json"
      params:
        file_format: "nested_json"
        locale_id: 81bd0e25f7d4cdd3da82d980db24534a
  push:
    sources:
    - file: "./master.csv"
      params:
        file_format: "csv"
        key_index: 1
        translation_index: 2
        comment_index: 3
        column_separator: ","
        quote_char: "\""
        locale_id: 626a0224e5e9620fbee69ceea2a1edae
